"use strict";
// 47都道府県（観測点は県庁所在地）。緯度経度は県庁所在地の代表値
const PREFS = [
  { slug: "hokkaido", pref: "北海道", city: "札幌", lat: 43.06, lng: 141.35 },
  { slug: "aomori", pref: "青森県", city: "青森", lat: 40.82, lng: 140.74 },
  { slug: "iwate", pref: "岩手県", city: "盛岡", lat: 39.70, lng: 141.15 },
  { slug: "miyagi", pref: "宮城県", city: "仙台", lat: 38.27, lng: 140.87 },
  { slug: "akita", pref: "秋田県", city: "秋田", lat: 39.72, lng: 140.10 },
  { slug: "yamagata", pref: "山形県", city: "山形", lat: 38.24, lng: 140.36 },
  { slug: "fukushima", pref: "福島県", city: "福島", lat: 37.75, lng: 140.47 },
  { slug: "ibaraki", pref: "茨城県", city: "水戸", lat: 36.34, lng: 140.45 },
  { slug: "tochigi", pref: "栃木県", city: "宇都宮", lat: 36.57, lng: 139.88 },
  { slug: "gunma", pref: "群馬県", city: "前橋", lat: 36.39, lng: 139.06 },
  { slug: "saitama", pref: "埼玉県", city: "さいたま", lat: 35.86, lng: 139.65 },
  { slug: "chiba", pref: "千葉県", city: "千葉", lat: 35.61, lng: 140.12 },
  { slug: "tokyo", pref: "東京都", city: "東京", lat: 35.69, lng: 139.69 },
  { slug: "kanagawa", pref: "神奈川県", city: "横浜", lat: 35.45, lng: 139.64 },
  { slug: "niigata", pref: "新潟県", city: "新潟", lat: 37.90, lng: 139.02 },
  { slug: "toyama", pref: "富山県", city: "富山", lat: 36.70, lng: 137.21 },
  { slug: "ishikawa", pref: "石川県", city: "金沢", lat: 36.59, lng: 136.63 },
  { slug: "fukui", pref: "福井県", city: "福井", lat: 36.07, lng: 136.22 },
  { slug: "yamanashi", pref: "山梨県", city: "甲府", lat: 35.66, lng: 138.57 },
  { slug: "nagano", pref: "長野県", city: "長野", lat: 36.65, lng: 138.18 },
  { slug: "gifu", pref: "岐阜県", city: "岐阜", lat: 35.39, lng: 136.72 },
  { slug: "shizuoka", pref: "静岡県", city: "静岡", lat: 34.98, lng: 138.38 },
  { slug: "aichi", pref: "愛知県", city: "名古屋", lat: 35.18, lng: 136.91 },
  { slug: "mie", pref: "三重県", city: "津", lat: 34.73, lng: 136.51 },
  { slug: "shiga", pref: "滋賀県", city: "大津", lat: 35.00, lng: 135.87 },
  { slug: "kyoto", pref: "京都府", city: "京都", lat: 35.02, lng: 135.76 },
  { slug: "osaka", pref: "大阪府", city: "大阪", lat: 34.69, lng: 135.50 },
  { slug: "hyogo", pref: "兵庫県", city: "神戸", lat: 34.69, lng: 135.20 },
  { slug: "nara", pref: "奈良県", city: "奈良", lat: 34.69, lng: 135.83 },
  { slug: "wakayama", pref: "和歌山県", city: "和歌山", lat: 34.23, lng: 135.17 },
  { slug: "tottori", pref: "鳥取県", city: "鳥取", lat: 35.50, lng: 134.24 },
  { slug: "shimane", pref: "島根県", city: "松江", lat: 35.47, lng: 133.05 },
  { slug: "okayama", pref: "岡山県", city: "岡山", lat: 34.66, lng: 133.93 },
  { slug: "hiroshima", pref: "広島県", city: "広島", lat: 34.40, lng: 132.46 },
  { slug: "yamaguchi", pref: "山口県", city: "山口", lat: 34.19, lng: 131.47 },
  { slug: "tokushima", pref: "徳島県", city: "徳島", lat: 34.07, lng: 134.56 },
  { slug: "kagawa", pref: "香川県", city: "高松", lat: 34.34, lng: 134.04 },
  { slug: "ehime", pref: "愛媛県", city: "松山", lat: 33.84, lng: 132.77 },
  { slug: "kochi", pref: "高知県", city: "高知", lat: 33.56, lng: 133.53 },
  { slug: "fukuoka", pref: "福岡県", city: "福岡", lat: 33.61, lng: 130.42 },
  { slug: "saga", pref: "佐賀県", city: "佐賀", lat: 33.25, lng: 130.30 },
  { slug: "nagasaki", pref: "長崎県", city: "長崎", lat: 32.74, lng: 129.87 },
  { slug: "kumamoto", pref: "熊本県", city: "熊本", lat: 32.79, lng: 130.74 },
  { slug: "oita", pref: "大分県", city: "大分", lat: 33.24, lng: 131.61 },
  { slug: "miyazaki", pref: "宮崎県", city: "宮崎", lat: 31.91, lng: 131.42 },
  { slug: "kagoshima", pref: "鹿児島県", city: "鹿児島", lat: 31.56, lng: 130.56 },
  { slug: "okinawa", pref: "沖縄県", city: "那覇", lat: 26.21, lng: 127.68 },
];

const REGIONS = {
  "北海道・東北": ["hokkaido", "aomori", "iwate", "miyagi", "akita", "yamagata", "fukushima"],
  "関東": ["ibaraki", "tochigi", "gunma", "saitama", "chiba", "tokyo", "kanagawa"],
  "中部": ["niigata", "toyama", "ishikawa", "fukui", "yamanashi", "nagano", "gifu", "shizuoka", "aichi"],
  "近畿": ["mie", "shiga", "kyoto", "osaka", "hyogo", "nara", "wakayama"],
  "中国": ["tottori", "shimane", "okayama", "hiroshima", "yamaguchi"],
  "四国": ["tokushima", "kagawa", "ehime", "kochi"],
  "九州・沖縄": ["fukuoka", "saga", "nagasaki", "kumamoto", "oita", "miyazaki", "kagoshima", "okinawa"],
};

// 隣接県（陸続き＋橋・主要航路）
const NEIGHBORS = {
  hokkaido: ["aomori"],
  aomori: ["hokkaido", "iwate", "akita"],
  iwate: ["aomori", "akita", "miyagi"],
  miyagi: ["iwate", "akita", "yamagata", "fukushima"],
  akita: ["aomori", "iwate", "miyagi", "yamagata"],
  yamagata: ["akita", "miyagi", "fukushima", "niigata"],
  fukushima: ["miyagi", "yamagata", "niigata", "gunma", "tochigi", "ibaraki"],
  ibaraki: ["fukushima", "tochigi", "saitama", "chiba"],
  tochigi: ["fukushima", "ibaraki", "gunma", "saitama"],
  gunma: ["fukushima", "tochigi", "saitama", "nagano", "niigata"],
  saitama: ["gunma", "tochigi", "ibaraki", "chiba", "tokyo", "yamanashi", "nagano"],
  chiba: ["ibaraki", "saitama", "tokyo"],
  tokyo: ["chiba", "saitama", "yamanashi", "kanagawa"],
  kanagawa: ["tokyo", "yamanashi", "shizuoka"],
  niigata: ["yamagata", "fukushima", "gunma", "nagano", "toyama"],
  toyama: ["niigata", "nagano", "gifu", "ishikawa"],
  ishikawa: ["toyama", "gifu", "fukui"],
  fukui: ["ishikawa", "gifu", "shiga", "kyoto"],
  yamanashi: ["tokyo", "saitama", "nagano", "shizuoka", "kanagawa"],
  nagano: ["niigata", "gunma", "saitama", "yamanashi", "shizuoka", "aichi", "gifu", "toyama"],
  gifu: ["toyama", "ishikawa", "fukui", "nagano", "aichi", "mie", "shiga"],
  shizuoka: ["kanagawa", "yamanashi", "nagano", "aichi"],
  aichi: ["shizuoka", "nagano", "gifu", "mie"],
  mie: ["aichi", "gifu", "shiga", "kyoto", "nara", "wakayama"],
  shiga: ["fukui", "gifu", "mie", "kyoto"],
  kyoto: ["fukui", "shiga", "mie", "nara", "osaka", "hyogo"],
  osaka: ["kyoto", "nara", "wakayama", "hyogo"],
  hyogo: ["kyoto", "osaka", "tottori", "okayama", "tokushima"],
  nara: ["kyoto", "osaka", "mie", "wakayama"],
  wakayama: ["osaka", "nara", "mie"],
  tottori: ["hyogo", "okayama", "shimane", "hiroshima"],
  shimane: ["tottori", "hiroshima", "yamaguchi"],
  okayama: ["hyogo", "tottori", "hiroshima", "kagawa"],
  hiroshima: ["okayama", "tottori", "shimane", "yamaguchi", "ehime"],
  yamaguchi: ["shimane", "hiroshima", "fukuoka"],
  tokushima: ["kagawa", "ehime", "kochi", "hyogo"],
  kagawa: ["tokushima", "ehime", "okayama"],
  ehime: ["kagawa", "tokushima", "kochi", "hiroshima"],
  kochi: ["tokushima", "ehime"],
  fukuoka: ["yamaguchi", "saga", "kumamoto", "oita"],
  saga: ["fukuoka", "nagasaki"],
  nagasaki: ["saga"],
  kumamoto: ["fukuoka", "oita", "miyazaki", "kagoshima"],
  oita: ["fukuoka", "kumamoto", "miyazaki"],
  miyazaki: ["oita", "kumamoto", "kagoshima"],
  kagoshima: ["kumamoto", "miyazaki", "okinawa"],
  okinawa: ["kagoshima"],
};

module.exports = { PREFS, REGIONS, NEIGHBORS };
